import { useState } from 'react';
import { Alert, Select, Stack, Text } from '@mantine/core';
import { useQuery } from '@tanstack/react-query';
import { academicApi } from '../../core/api/academic';
import type { SubjectDTO } from '../../core/api/dto/academic';
import { DataTable, type DataTableColumn } from '../../components/DataTable';
import { TableSkeleton } from '../../components/Skeleton';
import { PageHeader } from '../../components/PageHeader';
import { useTenant } from '../../core/context/useTenant';

const columns: DataTableColumn<SubjectDTO>[] = [
  { key: 'name', header: 'Name', render: (s) => s.name },
  { key: 'code', header: 'Code', render: (s) => s.code ?? '—' },
  { key: 'sort_order', header: 'Order', render: (s) => s.sort_order },
];

/**
 * Subjects are generated by the academic-year clone/template flow and are
 * read-only here (REQ-FE-AC-07 — no free-form structure CRUD).
 */
export function Subjects() {
  const { institutionId } = useTenant();
  const [yearId, setYearId] = useState<string | null>(null);

  const yearsQuery = useQuery({
    queryKey: ['academic-years', institutionId],
    queryFn: () => academicApi.listAcademicYears().then((r) => r.data),
    enabled: !!institutionId,
  });

  const subjectsQuery = useQuery({
    queryKey: ['subjects', institutionId, yearId],
    queryFn: () =>
      academicApi.listSubjects(yearId ?? undefined).then((r) => r.data),
    enabled: !!institutionId,
  });

  return (
    <>
      <PageHeader
        title="Subjects"
        subtitle="Subjects generated for the selected academic year."
        actions={
          <Select
            placeholder="Academic year"
            searchable
            clearable
            data={(yearsQuery.data ?? []).map((y) => ({
              value: y.id,
              label: y.name,
            }))}
            value={yearId}
            onChange={(value) => setYearId(value ?? '')}
            w={220}
          />
        }
      />

      <Stack gap="md">
        <Alert color="blue" variant="light">
          <Text size="sm">
            Subjects are created automatically when an academic year is cloned
            or generated from a template. They cannot be added or edited here.
          </Text>
        </Alert>

        {subjectsQuery.isLoading ? (
          <TableSkeleton rows={5} columns={3} />
        ) : (
          <DataTable
            columns={columns}
            rows={subjectsQuery.data ?? []}
            getRowKey={(s) => s.id}
          />
        )}
      </Stack>
    </>
  );
}
