import { Alert, Stack, Text } from '@mantine/core';
import { useQuery } from '@tanstack/react-query';
import { academicApi } from '../../core/api/academic';
import type { SubjectGroupDTO } from '../../core/api/dto/academic';
import { DataTable, type DataTableColumn } from '../../components/DataTable';
import { PageHeader } from '../../components/PageHeader';
import { useTenant } from '../../core/context/useTenant';

const columns: DataTableColumn<SubjectGroupDTO>[] = [
  { key: 'name', header: 'Name', render: (g) => g.name },
];

/**
 * Subject groups are generated by the academic-year clone/template flow and
 * are read-only here (REQ-FE-AC-07 — no free-form structure CRUD).
 */
export default function SubjectGroups() {
  const { institutionId } = useTenant();

  const groupsQuery = useQuery({
    queryKey: ['subject-groups', institutionId],
    queryFn: () => academicApi.listSubjectGroups().then((r) => r.data),
    enabled: !!institutionId,
  });

  return (
    <>
      <PageHeader
        title="Subject groups"
        subtitle="Subject groups for your institution."
      />

      <Stack gap="md">
        <Alert color="blue" variant="light">
          <Text size="sm">
            Subject groups are created automatically from the academic-year
            template. They cannot be added or edited here.
          </Text>
        </Alert>

        <DataTable
          columns={columns}
          rows={groupsQuery.data ?? []}
          getRowKey={(g) => g.id}
        />
      </Stack>
    </>
  );
}
